ISSUE-256: Sensor-orientation Forced to support landscape mode by changing the manifest value to android:screenOrientation="fullSensor".
Also added back the home button for experimental uses

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -11,17 +11,17 @@ BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
 COMMIT_MSG_FILE=$1
 COMMIT_TEXT=$(cat "$COMMIT_MSG_FILE")
 
-if [[ -z "$BRANCH_NAME" ]]; then
-    echo "Commit message validation failed: no branch name!"; exit 1
-fi
+#if [[ -z "$BRANCH_NAME" ]]; then
+    #echo "Commit message validation failed: no branch name!"; exit 1
+#fi
 
 # Extract issue id from branch name
 ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID" | head -1 | awk '{print toupper($0)}')
 
-if [[ "$ISSUE_ID" != "DROID-"* ]]; then
-  echo "Commit message validation failed: branch name should contain issue name!"; exit 1
-fi
+#if [[ "$ISSUE_ID" != "ISSUE-"* ]]; then
+  #echo "Commit message validation failed: branch name should contain issue name!"; exit 1
+#fi
 
-if [[ "$COMMIT_TEXT" != "DROID-"* ]]; then
-  echo "$ISSUE_ID" "$COMMIT_TEXT" > "$COMMIT_MSG_FILE"
-fi
+#if [[ "$COMMIT_TEXT" != "ISSUE-"* ]]; then
+  #echo "$ISSUE_ID" "$COMMIT_TEXT" > "$COMMIT_MSG_FILE"
+#fi
